spring.application.name=BattlescrollService
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.upload-dir=${UPLOAD_DIR:BattlescrollService/public/images}
#UPLOAD_DIR pour docker
#spring.web.resources.static-locations=classpath:/public/,file:${app.upload-dir}
spring.web.resources.static-locations=file:${app.upload-dir}
server.port=8082